# Generated by Django 3.0.8 on 2020-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
                ('Video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
